import numpy as np
import tensorflow as tf
import timeit
import matplotlib.pyplot as plt

trials = 30
p_vals = list(np.logspace(-50, 0,num=trials,base=1.075))
t_conv = []
t_casual = []
t_sparse = []

for p_val in p_vals:
    test_tensor = tf.constant(np.random.binomial(n=1,p=p_val,size=(3000,3000))*(1+np.random.poisson(lam=1,size=(3000,3000))))
    sparse_test_tensor = tf.sparse.from_dense(test_tensor)
    t_conv.append(timeit.timeit(lambda : tf.sparse.from_dense(test_tensor), number = 20)/20)
    t_casual.append(timeit.timeit(lambda : tf.matmul(test_tensor,test_tensor), number = 1))
    t_sparse.append(timeit.timeit(lambda : tf.sparse.sparse_dense_matmul(sparse_test_tensor,test_tensor), number = 1))
    
plt.plot(p_vals,t_conv,label='Conversion time')
plt.plot(p_vals,t_casual, label='Plain matmul')
plt.plot(p_vals,t_sparse, label='Sparse matmul')
plt.xlabel('density')
plt.ylabel('time (in secs)')
plt.legend()
plt.show()

print(next(p for p,c,s in zip(p_vals, t_casual, t_sparse) if c <= s))

print((t_sparse[-1]-t_sparse[0])/(p_vals[-1]-p_vals[0]))

print(min(t_sparse),max(t_sparse),np.mean(t_casual))

text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at enim ut lacus tempor vulputate. Integer finibus sem non ante imperdiet tempus. Nulla vel velit quis mauris efficitur ullamcorper sed eget magna. Pellentesque blandit, tellus quis dictum aliquam, elit elit efficitur ligula, vitae fermentum leo lectus quis dolor. In sed augue diam. Vivamus fermentum dapibus libero eu tristique. Morbi id egestas dolor. Integer viverra, leo vel vulputate accumsan, purus massa tincidunt eros, venenatis sollicitudin arcu magna ut lorem. Donec aliquet est vitae consectetur tempor. Quisque sollicitudin sodales odio, et iaculis velit. Nullam tellus magna, vestibulum eget lobortis non, accumsan ut erat. Etiam cursus, lectus vel accumsan sodales, orci sapien imperdiet elit, sit amet placerat tellus risus quis lacus. Etiam posuere consectetur est, faucibus vestibulum neque. In eu vehicula leo, quis scelerisque neque.

Mauris diam dolor, tempor ut pellentesque sit amet, gravida nec libero. Etiam porttitor dui justo. Etiam nec finibus orci, sit amet convallis risus. Cras dui mi, condimentum non imperdiet id, commodo at odio. Suspendisse molestie lectus a libero rutrum vehicula. Donec sit amet est nec eros efficitur pretium mollis eu eros. Phasellus eu urna non orci egestas scelerisque. Suspendisse ut turpis eget nisl scelerisque dictum. Donec dignissim mollis urna, at fermentum leo pellentesque sit amet. Fusce imperdiet lobortis sapien, eget vehicula nunc lacinia nec. Donec placerat ipsum at nisl egestas finibus. Sed bibendum auctor feugiat.

Fusce at nibh mollis orci efficitur rutrum at sit amet quam. In tincidunt leo eu lorem placerat eleifend a non nulla. Curabitur semper, lacus in venenatis ornare, enim nisi hendrerit lacus, ac pulvinar massa risus eu mi. Fusce laoreet felis libero, eget sagittis libero imperdiet ut. Integer dictum libero sit amet rhoncus consectetur. Vivamus ac mi id erat pharetra vehicula. Curabitur ultrices, est ut rhoncus ullamcorper, nisl diam egestas dui, a consequat metus mauris non neque. Vivamus sapien orci, interdum nec nisl vel, sollicitudin pulvinar libero. Aenean feugiat lorem elit, at rutrum turpis porta eu. Duis condimentum metus tempor eros lacinia iaculis. In egestas nibh et arcu finibus tempus. Sed fermentum elit quis purus malesuada posuere id quis libero.

Fusce augue nulla, imperdiet vitae risus a, tempor tempus sem. Ut ante ligula, tempor quis enim at, eleifend vulputate nibh. Donec gravida odio euismod augue dignissim dignissim. Proin at erat ipsum. Integer ac nisi enim. Morbi in ex est. Sed interdum eleifend tortor non sollicitudin. Cras vulputate quis sem vel egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vitae finibus nisi. Sed tempor tortor in auctor ultricies. Vivamus posuere varius erat, et aliquam risus feugiat ac. Suspendisse id lectus augue. Nam rhoncus vulputate neque eu viverra.

Pellentesque eu elementum ante. Sed sit amet blandit nisl, quis commodo diam. Duis hendrerit ex velit, eget consectetur ipsum imperdiet ut. Quisque placerat, nisi eget scelerisque dictum, mauris neque congue lectus, quis pharetra diam orci et nunc. Morbi dolor ipsum, fringilla vel consectetur eu, ultrices posuere est. Praesent eu sapien vestibulum nisi iaculis egestas ut sed nibh. Proin fringilla molestie fringilla. Cras tincidunt dui eget eros cursus vehicula. Cras venenatis, felis ac interdum elementum, nisi sapien ornare lectus, ac porttitor lectus metus ut urna. Duis ac scelerisque dui. Nam eget dignissim turpis, a convallis enim. Quisque eget leo auctor, posuere sapien quis, viverra augue.

Donec nisi magna, aliquet in lectus luctus, lobortis feugiat tellus. Pellentesque convallis tristique orci, varius egestas lectus accumsan vitae. Donec tincidunt cursus mollis. Donec scelerisque interdum lorem at eleifend. Integer laoreet sit amet nisi quis venenatis. Vivamus maximus turpis purus, id bibendum sapien iaculis quis. Nam nisi tortor, auctor et enim vel, pellentesque consequat ante. Nunc faucibus lorem non diam tincidunt, eu suscipit turpis tincidunt.

In viverra leo vitae vulputate porta. Maecenas egestas arcu ac neque volutpat, vitae venenatis quam fermentum. Maecenas ut pretium urna, et viverra massa. Sed urna felis, porta eget arcu in, pharetra scelerisque massa. Sed congue enim enim, sed placerat metus molestie a. Nunc feugiat congue dui sit amet rhoncus. Vivamus euismod nisi quis sodales vulputate. Quisque sed nulla ultricies, euismod odio vitae, fringilla diam. Fusce gravida, mauris at finibus tincidunt, diam tortor varius magna, vitae mollis quam turpis id urna.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Quisque at massa fermentum, dictum eros eget, mollis arcu. Aenean et orci et magna sodales semper quis a sapien. Suspendisse nec libero ipsum. Sed ut nisl hendrerit, interdum massa id, tristique tortor. Sed ac ligula vitae sapien tincidunt ultrices eu at enim. Nullam massa lacus, condimentum et massa non, viverra ullamcorper purus.

Vivamus quis commodo sapien. Maecenas fringilla nunc vel nunc lacinia tempor. Praesent velit magna, suscipit ac ante eu, elementum eleifend metus. Morbi et interdum ex. Donec id tristique justo. Vestibulum vitae scelerisque neque. Aenean pellentesque ipsum est, eu aliquam ligula egestas id. Morbi molestie ut metus sed dapibus. Pellentesque enim magna, lobortis quis cursus eget, iaculis at turpis. Donec suscipit in augue imperdiet sagittis. Integer vehicula semper lectus eu euismod. Nulla tempor sodales efficitur. Nulla porta ipsum sit amet massa iaculis, quis dignissim nisi ultrices. Vivamus auctor eleifend fringilla. Mauris fermentum at ante nec fermentum. Fusce in nulla tempus, euismod sem tempor, feugiat velit.

Nam egestas dapibus lorem, eu efficitur nibh viverra imperdiet. Aliquam hendrerit ex magna, eget scelerisque ante dictum quis. Pellentesque quis aliquam elit, ac condimentum sem. Integer in tincidunt massa. Praesent convallis massa vel dignissim pretium. Duis sodales ullamcorper rhoncus. Ut aliquet auctor ligula sed sagittis. Nunc ac dignissim turpis. Sed pulvinar laoreet lobortis.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc aliquet vel turpis nec posuere. Suspendisse ac luctus urna. Quisque tincidunt orci sapien, sed tempus neque bibendum eu. Nam auctor risus purus, ut ultricies lacus vehicula a. Aenean non neque ex. Suspendisse eget neque quis lectus elementum efficitur ac vel nunc. Vestibulum lacinia auctor magna sit amet porta. Mauris dapibus consequat laoreet. Phasellus ornare, ante id facilisis condimentum, sem lorem feugiat magna, quis lobortis turpis massa a ligula. Nulla tincidunt justo justo, et eleifend odio iaculis ut. Aliquam congue congue feugiat. Donec id gravida dolor. Donec eget molestie erat, eget placerat ex. Integer est velit, dapibus ut porttitor volutpat, luctus sed leo. Maecenas congue nunc enim.

Cras fringilla ac arcu nec venenatis. Ut diam augue, venenatis a magna a, lacinia gravida ex. Aenean id velit semper, convallis arcu ac, congue odio. Donec vulputate ac ex in pulvinar. Suspendisse varius, massa a interdum lobortis, lectus nibh commodo urna, non lobortis ante nisi at sem. Vestibulum ac dui vel nisl luctus dictum. Maecenas id dui tristique, suscipit est in, consectetur lorem. Suspendisse non fermentum velit. Praesent ultricies cursus quam, id porta urna rutrum a. Nam faucibus rhoncus massa, a ultrices risus pulvinar a. Nullam egestas fringilla dictum. Morbi eros purus, pretium elementum libero sed, consequat consequat enim. Vestibulum fermentum risus a porttitor molestie. Proin ultricies consectetur augue ac fringilla.

Pellentesque luctus consequat arcu sit amet cursus. Donec posuere ac purus vitae auctor. Ut aliquam tristique leo, at condimentum sapien pharetra non. Donec vitae nibh auctor, consequat quam ut, fringilla turpis. In quis mi ac nulla commodo ullamcorper. Phasellus molestie venenatis nibh ac faucibus. Cras dictum rutrum lacus. Phasellus at dictum risus. Maecenas dignissim, est at porta gravida, arcu felis pretium arcu, vel blandit eros eros non eros. Nullam porta elit nec magna consectetur, a sollicitudin est bibendum. Sed convallis vulputate dapibus. Cras a ante ligula. Vivamus pellentesque ante ligula, ut efficitur elit tempus varius. Integer velit mi, pulvinar non urna eu, consectetur fringilla nisi.

Sed quis massa consectetur, tempor turpis nec, commodo dolor. Proin sagittis lacus iaculis fermentum ultrices. Donec porttitor enim eget diam pellentesque, at tincidunt odio efficitur. Sed tristique gravida ante id dictum. Etiam a facilisis lorem, nec accumsan sem. Maecenas et faucibus nunc. Vestibulum vitae dui ut erat pharetra mollis. Quisque suscipit est nec quam tincidunt egestas. Aenean eu elit vulputate, sagittis turpis at, accumsan orci. Aenean dignissim molestie sagittis. Vestibulum pulvinar semper tortor, vel feugiat erat auctor quis. Etiam porttitor porttitor sapien, sed dictum mauris semper eget.

Pellentesque ultrices quis odio eu ullamcorper. Quisque non luctus urna. Cras at tempus leo. Praesent auctor feugiat urna, sed tempus tellus rutrum et. Fusce hendrerit efficitur mauris, in tristique erat. Duis sit amet lacus at ligula tempus semper. Mauris maximus sit amet ipsum vitae sodales. Integer tincidunt sed ex egestas fermentum. Aliquam blandit, augue in interdum viverra, nisl enim malesuada turpis, id ullamcorper libero ligula bibendum nisl. Sed vestibulum magna nibh, sit amet auctor sapien eleifend eget. Quisque nec vestibulum quam. Aenean non sodales dolor. Duis at odio eu arcu faucibus pharetra ut a ipsum.

Sed sodales ex nec tortor blandit venenatis. Praesent ut nunc ac sapien elementum convallis quis sit amet nulla. Praesent ligula erat, tincidunt non justo id, suscipit auctor quam. Aliquam semper sodales nunc non feugiat. Vivamus a odio mauris. Quisque commodo purus sed ligula aliquet, vitae ultricies tortor laoreet. In eget sollicitudin metus. Morbi semper turpis sit amet sem bibendum, in porttitor lorem rhoncus. Nullam commodo volutpat felis, in vestibulum velit ultricies posuere. Mauris auctor convallis elit et mattis. Aenean sagittis mauris ut neque mollis, vitae viverra augue aliquet.

Sed fringilla nulla nec euismod interdum. Ut auctor eros quis lobortis ullamcorper. Aliquam bibendum risus rutrum condimentum accumsan. Donec ac ex sodales dolor vestibulum tristique. Ut urna purus, congue iaculis est quis, porta vehicula nibh. Integer mollis augue ut dignissim suscipit. Nullam ac elit vitae nisi congue facilisis id vitae urna. Vivamus ut fermentum mi. Quisque laoreet ante lectus, vel vulputate sapien malesuada vel. Nullam laoreet, sem a venenatis posuere, neque justo efficitur mauris, a posuere nisl leo nec nulla. Etiam lacinia tortor eget felis egestas, in euismod eros pharetra.

Cras interdum lorem at mi egestas, eu venenatis diam euismod. Vestibulum facilisis urna nulla, at placerat erat porttitor nec. Donec fringilla ligula justo, sed facilisis tellus mattis nec. Nullam ac sem nec ante pellentesque elementum at eget sem. Etiam euismod dictum ex ac mollis. Curabitur ac mi sed dui blandit euismod vel tempor tellus. Phasellus molestie nec dui id lacinia. Donec quis ipsum sed mi bibendum hendrerit. Maecenas dolor lorem, gravida a urna at, blandit pretium magna. Integer condimentum nisl scelerisque viverra porttitor. Aenean porta, quam in hendrerit convallis, enim erat venenatis urna, at faucibus dui leo eu felis.

Etiam quis est molestie odio faucibus egestas. Nulla vel ultricies est, sit amet efficitur lorem. Vivamus volutpat lacinia consequat. Donec et sollicitudin risus. Nulla risus tortor, iaculis non massa vitae, sodales bibendum justo. Vivamus volutpat, purus id tincidunt efficitur, arcu mauris condimentum dui, a maximus ipsum ante ut nulla. Praesent euismod ullamcorper nulla vel posuere. Pellentesque in maximus orci. Cras convallis eget libero nec consequat. Nullam arcu metus, pharetra ut justo nec, scelerisque sagittis dui. Phasellus hendrerit ligula quis porta pulvinar. Nunc at mi in tellus iaculis luctus. Duis viverra faucibus lorem consectetur vulputate.

Phasellus lobortis ut odio vitae feugiat. Donec eget ipsum tristique, suscipit sem nec, porta nulla. Morbi semper libero ut massa blandit porta. Integer eu varius ligula. Nulla molestie libero et erat tempor, non mattis justo feugiat. Fusce risus mauris, faucibus vitae tincidunt ac, ornare lobortis magna. Fusce egestas aliquam quam, a rutrum ex imperdiet hendrerit. Nunc nunc augue, convallis ut ultricies a, ultricies et turpis. Aenean sit amet lobortis mi. Aliquam elit leo, pulvinar quis luctus id, suscipit sed nibh. Aenean quis urna quis eros efficitur imperdiet nec eget erat.

Phasellus ut augue sem. Pellentesque suscipit felis sit amet elit aliquam congue. Sed ultrices eget enim et porta. Integer varius nunc et libero condimentum, quis pretium libero lacinia. Aliquam vulputate turpis ultrices felis auctor, eget pharetra dolor consectetur. Vivamus at leo vitae nisl faucibus mollis. Fusce consequat hendrerit placerat. Praesent pellentesque ut nulla sed dictum. Fusce at commodo nunc. Donec eget vestibulum dolor.

Fusce feugiat urna dolor, a dignissim est egestas a. Nulla malesuada erat mollis, dapibus elit sed, faucibus odio. Vestibulum tincidunt placerat tellus, eget luctus tortor posuere vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet mauris ac massa condimentum, nec lacinia nulla gravida. Nullam vel tortor vel lacus vestibulum maximus eget non ante. Etiam fringilla leo turpis.

Pellentesque viverra nibh quis sapien euismod lobortis. Sed posuere vehicula sapien, id porttitor libero sodales ac. Suspendisse accumsan malesuada lacus quis lobortis. Quisque nec odio pretium, convallis mauris vitae, bibendum mauris. Vivamus placerat urna in mollis aliquam. Sed consectetur auctor porttitor. Praesent quis odio ut felis ultrices faucibus. Quisque pharetra urna metus, vitae ultricies dui consequat sed. Cras mollis, dui commodo finibus fringilla, magna velit lacinia nunc, quis ultrices purus urna quis lorem. Vivamus vitae euismod ex. Proin ullamcorper et dui quis blandit. Ut sit amet dolor non dolor maximus faucibus. Suspendisse potenti. Curabitur porttitor mauris quis purus tempor suscipit.

Integer eget eros sagittis, auctor sapien vel, fringilla orci. Pellentesque enim augue, volutpat vitae nunc in, condimentum imperdiet nisl. Phasellus aliquam est sed nunc blandit, eget maximus ante commodo. Proin sit amet purus et tortor consectetur facilisis nec sed velit. Proin ultrices lorem vitae aliquet congue. Etiam facilisis lorem elit, sit amet pulvinar dolor gravida vel. Integer est enim, varius et ante non, egestas pellentesque quam.

In posuere, ante eu vulputate molestie, ligula eros vestibulum tortor, sit amet aliquet eros lorem id sem. Integer non massa mollis, vehicula elit sit amet, hendrerit odio. Proin aliquet viverra lectus, eget scelerisque dolor congue sit amet. Praesent dictum orci id neque ultrices fringilla at non orci. Praesent pretium justo eget ipsum maximus, id ullamcorper dui porttitor. Morbi volutpat dolor nulla, eget finibus nunc ornare non. Quisque fringilla sed tellus ut aliquet. Nam non quam in sapien aliquet vehicula condimentum a diam. Donec sed vehicula dolor. Morbi convallis semper bibendum. Nam quis tellus ipsum. Aliquam erat volutpat. In hac habitasse platea dictumst. Sed vel bibendum ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus.

In sollicitudin quam vitae massa venenatis, in bibendum justo finibus. In pulvinar nec ante et imperdiet. Suspendisse sagittis tellus eu urna accumsan, eget cursus felis iaculis. Aliquam erat volutpat. Morbi facilisis orci ut sagittis vulputate. Sed et commodo felis. Donec ultrices purus vitae urna luctus volutpat. Sed eu faucibus urna, sed sodales magna. Vestibulum quis molestie urna, sit amet faucibus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam lacinia molestie mauris ut laoreet. Donec urna ex, eleifend a magna a, placerat pellentesque leo. Phasellus sed ex vel risus molestie porta at et quam. Nam malesuada nibh sem, non scelerisque neque sollicitudin quis. Quisque consequat tempor magna, ut mattis est mattis in.

Maecenas lacinia feugiat ipsum. In felis mi, finibus eu euismod et, congue at magna. Mauris lacus libero, volutpat sed blandit ut, fermentum ac nunc. Nam vitae commodo urna, ut dignissim dui. Vivamus efficitur pellentesque interdum. Donec dui augue, fermentum eget aliquet sit amet, imperdiet a velit. Sed quis vulputate lorem. Mauris congue blandit nisi, non gravida dui tincidunt sit amet. Suspendisse nisl felis, tincidunt aliquet mauris accumsan, pulvinar pellentesque augue. Nullam egestas arcu et sapien finibus condimentum. Aenean lobortis sapien sit amet pulvinar vulputate.

Mauris malesuada orci et enim rutrum feugiat. Fusce vestibulum dapibus maximus. Nam elementum metus est, sed mollis augue vestibulum id. Nullam ante felis, suscipit blandit consequat sit amet, mollis eget urna. Integer sodales tempor elementum. Nunc nec volutpat diam. Quisque fermentum finibus turpis, non imperdiet ante blandit at. Vivamus risus lectus, laoreet vel convallis eget, posuere vel risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam pretium ex a enim consequat, sed feugiat dui scelerisque. Fusce egestas sem et orci molestie tincidunt. Pellentesque vitae velit vel orci vulputate consectetur eget sit amet leo. Integer ultricies velit diam, vel molestie est gravida quis. Phasellus molestie, urna eu blandit mollis, lacus nibh pharetra tortor, ut suscipit lectus ante quis turpis.

Curabitur eu ex vehicula, molestie turpis et, volutpat risus. Nunc iaculis dolor vel justo fringilla vehicula. Praesent consequat metus in fringilla accumsan. Duis vel viverra arcu, et ultricies arcu. Proin et quam quis nisl lacinia placerat. Fusce auctor congue felis quis pellentesque. Nam aliquet nibh non ornare efficitur. Duis facilisis laoreet leo ultrices imperdiet. Integer ut velit vel leo tempor convallis. Phasellus metus quam, elementum malesuada enim vel, viverra rutrum metus. Duis a neque posuere, maximus purus ut, porttitor orci. Nunc volutpat mi non dolor molestie, ac eleifend urna vehicula. Integer sodales, tellus sed tristique pulvinar, diam ex consectetur lorem, ut facilisis est felis nec sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Quisque nisi augue, egestas a accumsan vel, vehicula et sem. Nulla facilisi. Nunc consequat felis vitae libero efficitur tempor. Cras pretium mauris ac facilisis bibendum. Duis fermentum non nibh et posuere. Duis vestibulum at nisl et posuere. Aliquam mattis venenatis diam ut bibendum. Ut ut dignissim est.

Aliquam nibh nunc, rhoncus vel pretium eu, varius id dolor. Nulla a fringilla mi, id sollicitudin nisl. Donec molestie laoreet odio, vel dignissim sem convallis nec. Aliquam sed sapien eros. Cras hendrerit bibendum magna id finibus. Vestibulum aliquam leo ipsum, non maximus sem viverra sit amet. Etiam non ex dui. Proin sapien turpis, molestie a viverra eget, congue non est. Quisque diam quam, pretium at ornare a, eleifend nec neque. Curabitur mollis tellus est, id iaculis nunc dictum non. Praesent scelerisque nisl quis dui bibendum venenatis. Pellentesque in purus feugiat nisl suscipit auctor eget nec justo. Sed luctus finibus nisl, nec iaculis ante bibendum vitae. Vestibulum aliquam luctus metus id vulputate. Etiam magna risus, tincidunt et mi eu, accumsan gravida urna. Sed quis libero elit.

Vestibulum in dapibus quam. Sed faucibus, ex quis euismod ultrices, nibh ex lacinia sem, placerat tristique justo enim eget nunc. Nunc nec dui quis lacus mattis varius. Ut aliquet pretium ante, eget egestas massa sagittis ut. Nulla porttitor lorem eget tellus faucibus, in dictum nisi imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget ex eu odio iaculis condimentum. Ut eleifend gravida nunc nec efficitur.

Aenean pretium arcu et turpis facilisis, fermentum convallis velit luctus. Nulla interdum venenatis orci, ut condimentum purus auctor a. Suspendisse tempor pellentesque mauris quis convallis. Maecenas non augue urna. Sed sit amet ante lorem. Maecenas efficitur leo vel porttitor dapibus. Suspendisse faucibus egestas nunc eget bibendum. Donec faucibus convallis ipsum, in malesuada magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc hendrerit metus eget nibh volutpat dictum. Aliquam at dapibus magna. Vivamus sodales vulputate dui condimentum lobortis. Integer ut odio eget velit posuere congue.

Etiam pellentesque pellentesque mi. Ut euismod mattis mi, at tempus sem tempor a. Mauris hendrerit vestibulum feugiat. Suspendisse rhoncus neque blandit nisi vehicula tempus. Aliquam erat volutpat. Nam congue ex a ultricies pellentesque. Cras molestie lacus placerat quam consectetur efficitur. Praesent interdum et enim quis aliquet. Sed et dui pharetra, rutrum nisi ut, mollis orci. Nulla imperdiet semper vehicula. Proin orci nulla, convallis vel dolor vel, maximus facilisis turpis. Morbi et aliquet neque, vitae sollicitudin eros.

Aliquam lobortis sollicitudin elit, eget dapibus mauris porta nec. Pellentesque elementum, tellus quis hendrerit porttitor, massa mauris sagittis dolor, porta tempus dui urna eu ex. Quisque congue pellentesque diam. Cras lacinia suscipit purus sit amet volutpat. Vestibulum faucibus elit nec nibh commodo varius. Nunc eu viverra tortor, sed placerat lectus. Vestibulum accumsan felis ac urna elementum mattis. Suspendisse lacus massa, convallis vel augue a, sodales feugiat dolor. Vivamus ultrices sed ex vel interdum. Sed quis lectus lacus. Nunc dictum pellentesque magna, quis malesuada lacus. Pellentesque sit amet libero eros. Donec malesuada nunc ex, ut pellentesque enim mollis ac. Fusce egestas pellentesque eros. Etiam id risus eu neque porta consequat. In neque justo, scelerisque eget laoreet et, ultrices eget eros.

Nunc lobortis cursus porta. Sed ultricies posuere arcu, eu porta magna feugiat nec. Nam mattis quam ut arcu lobortis pellentesque. Maecenas leo magna, malesuada vitae malesuada quis, tincidunt id neque. Nunc consequat vehicula sem at tempor. Integer viverra sed diam sit amet iaculis. Integer non metus nec elit vehicula congue at vitae nisi. Donec condimentum ipsum vitae dignissim pharetra. Ut ultricies erat nisl, id facilisis dolor porta id. Sed a nibh ipsum. Praesent eu vestibulum leo, ut venenatis nisi. Ut id auctor arcu, non vehicula dui.

In mollis dui non consectetur semper. Pellentesque congue arcu id malesuada viverra. Pellentesque consectetur, diam at finibus pulvinar, nulla mauris cursus nulla, dignissim tempor elit purus et est. Sed suscipit tortor eget aliquet fringilla. Nullam sagittis arcu dolor, vel iaculis nunc cursus sit amet. Aliquam a ultrices tellus, nec imperdiet est. Aenean molestie rutrum leo, sed viverra tellus scelerisque eu. Vestibulum vel elit et urna sodales porta. Aenean imperdiet sagittis turpis ut tempor. Quisque volutpat sit amet orci sit amet ornare. Sed sodales lectus nec eleifend mattis. Donec egestas scelerisque odio eu convallis.

Nam molestie nulla nisl, vel placerat lectus dapibus euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec consequat tellus et est ultricies pharetra. Proin eu euismod dui. Quisque ac massa ex. Donec non tincidunt nisl. Aliquam erat volutpat. In mollis lacus in ligula molestie luctus. Nunc nibh arcu, facilisis et massa dictum, lacinia convallis arcu. Aenean fermentum venenatis mattis. Donec ultricies turpis ut diam tincidunt gravida. Nunc ultricies magna nunc, vitae tincidunt dui tincidunt a.

Curabitur auctor ac mauris a egestas. Quisque elementum, lectus eu efficitur imperdiet, purus ipsum sodales arcu, ut pulvinar nisi justo et nisi. Cras non mollis elit. Nullam mollis nisi nec ante consequat, in viverra lectus luctus. Ut condimentum ornare consectetur. Nam at fermentum purus, quis tristique leo. In aliquam ultricies odio, eget semper odio condimentum in. Pellentesque sodales tempus risus, sit amet mollis nunc. In blandit est ut elementum laoreet. Vestibulum sit amet varius sem. Cras pharetra, mi ut finibus volutpat, dolor sapien elementum felis, vel ornare sapien turpis et nibh. Suspendisse semper, nisl ac rhoncus molestie, felis libero consequat dui, laoreet venenatis elit augue sed est. Nullam faucibus nulla magna, varius rhoncus turpis pharetra a. Nunc egestas, tortor ac maximus vulputate, erat augue finibus ipsum, ut aliquam sem ex non ante. Pellentesque tincidunt mattis urna sed semper.

Praesent a libero ligula. Etiam elit libero, tempus ut rhoncus a, finibus et ipsum. Vestibulum cursus quis justo in dictum. Aliquam elementum, risus efficitur feugiat vestibulum, urna erat interdum nibh, posuere aliquet tortor est vitae odio. Quisque ornare urna eu neque interdum, a vulputate lorem viverra. Mauris mattis elit a quam tincidunt, eu euismod odio lobortis. In mattis turpis quam, bibendum maximus leo euismod quis. Vestibulum nisl eros, commodo et purus in, dignissim pretium metus.

Sed pellentesque justo sed est commodo, sed euismod diam pellentesque. Nunc volutpat dui vel tortor suscipit pellentesque. Sed massa dui, placerat sit amet sapien et, volutpat ornare justo. Sed lobortis tempor ligula vel sodales. Integer non congue arcu. Praesent congue molestie sem, eget semper tortor ultricies ut. Aenean facilisis odio et nibh commodo, sodales malesuada est varius. Ut faucibus nisl sed ante lobortis volutpat. Maecenas nec purus eget tellus interdum consequat.

Sed tristique ex mi, ac vehicula est efficitur at. Sed nisl lectus, dignissim a rhoncus vitae, posuere nec tortor. Donec in libero consectetur, mollis risus in, sagittis nulla. Nulla ac nisi euismod, mattis est eget, sollicitudin metus. Aenean purus nulla, fermentum sed efficitur id, accumsan id metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla in dui mi. Fusce suscipit felis sit amet rhoncus accumsan. Pellentesque enim turpis, bibendum quis scelerisque non, ultrices id magna. Vivamus eleifend gravida mauris, id aliquet eros maximus sagittis.

In blandit malesuada mi nec porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec ligula augue, porta eget viverra ut, elementum nec eros. Donec nec gravida lacus. Fusce sit amet fringilla nisi, vel volutpat turpis. Vestibulum ultricies leo non mauris cursus pulvinar. Maecenas ullamcorper facilisis est, vel facilisis massa vestibulum vel. Aenean ac luctus odio. Nam velit dolor, tempus vel arcu non, tristique aliquet augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum pharetra aliquet ante. Donec interdum semper nibh, dictum iaculis est.

In suscipit, eros in vestibulum venenatis, mauris quam interdum dolor, vitae ultrices magna est non mauris. Sed tellus ligula, consectetur et nunc sit amet, ultrices porttitor dolor. Duis dignissim tortor eget risus accumsan gravida. In feugiat lorem odio, ut gravida mi feugiat at. Nunc auctor venenatis metus vel porta. Proin sagittis iaculis nisi, sed cursus libero gravida vel. Pellentesque magna metus, sagittis at varius non, fringilla et ipsum. Mauris non nunc sed ipsum lacinia euismod. Praesent non ipsum et nunc lacinia tempus at id dui. Nunc rhoncus mattis ligula vitae accumsan. Nunc cursus posuere nibh id viverra. Proin faucibus commodo consectetur. Morbi vitae mauris nec dui ultricies mattis et at massa. Morbi maximus quam libero, nec blandit metus gravida ut.

Nullam varius velit a turpis placerat, quis luctus orci porttitor. Nulla at tortor et enim varius pellentesque in eget magna. In rhoncus libero non luctus egestas. Nam ut venenatis leo, sed vehicula nibh. Cras dui sem, vehicula eu varius nec, interdum id neque. Ut aliquet augue est, vel suscipit felis mollis eget. Suspendisse eget consequat nibh. Mauris tempus nunc mi, ac blandit dui malesuada in. Pellentesque molestie porttitor nulla sed tincidunt. Vestibulum sodales orci at quam sodales, eu ornare dolor sollicitudin.

Maecenas dapibus rhoncus libero vitae laoreet. Vivamus tincidunt, ex a ornare maximus, elit ipsum maximus dui, et tincidunt sem augue a massa. Nam commodo mi non posuere pharetra. Proin malesuada molestie ligula quis faucibus. Donec euismod et libero non ultrices. Nullam egestas ligula nisl. Maecenas blandit, ligula vitae convallis ullamcorper, libero dui rutrum risus, in sagittis arcu nunc in velit. Mauris gravida convallis quam, non semper turpis auctor id. Mauris non sodales mauris, eu mollis lorem.

Morbi tempus tempor turpis, at vulputate massa luctus eu. Integer eu pulvinar est. Ut eu neque at ipsum malesuada malesuada non sit amet sem. Quisque in dolor a ex ultricies pellentesque sed a tortor. Nullam facilisis in dui nec pharetra. Donec placerat efficitur risus, quis efficitur augue sodales vel. Fusce lacinia elementum arcu id lobortis. Proin scelerisque nec nunc id pellentesque.

Maecenas aliquet, libero eu mattis suscipit, libero urna rhoncus magna, tempus facilisis nulla purus non lacus. Vivamus viverra luctus tortor vel varius. Praesent ornare lobortis magna, quis elementum tortor fringilla ut. Donec sodales erat sed ipsum hendrerit, sit amet mattis nibh condimentum. Donec vestibulum mi tellus, in sodales turpis semper non. Maecenas porta nisl sit amet pellentesque laoreet. Donec eu tincidunt augue. Quisque sed sodales leo. Suspendisse ultricies eget leo id varius. Ut malesuada quis enim id ultrices. Quisque ut risus fermentum libero condimentum tempus vestibulum ut ligula. Duis euismod, augue sed condimentum interdum, libero justo rhoncus massa, non fringilla purus ex ac nisl. Nam condimentum ipsum sit amet quam dignissim, posuere porta ante tempor.

Donec erat lectus, pretium ac euismod id, aliquam non odio. Integer justo metus, sollicitudin a ante eget, sagittis finibus eros. Aenean quis purus ut dui gravida faucibus non molestie neque. Donec convallis nulla odio, aliquet porta quam ultricies nec. In facilisis laoreet congue. Ut ut ligula sed ligula tempus posuere consectetur quis quam. Nulla dignissim augue libero, sit amet porta risus pharetra in. Integer eleifend dapibus risus, vel feugiat nunc consequat in. Duis vehicula sem congue lorem blandit, sit amet facilisis metus condimentum.

Proin aliquam vitae leo pulvinar blandit. Sed et eros nec neque maximus fermentum. Nunc blandit nibh purus, ac imperdiet enim laoreet non. Donec iaculis pharetra ex, sit amet laoreet magna iaculis rutrum. Aliquam sed ornare tortor. Quisque volutpat volutpat urna, nec volutpat libero facilisis vitae. Vivamus auctor congue velit, ut auctor orci interdum non. Morbi volutpat maximus est non lacinia. Phasellus mi urna, malesuada quis elementum nec, pulvinar sit amet justo. Donec ac euismod ex. Quisque vel venenatis orci. Aliquam erat volutpat.

Quisque sed arcu a lorem fermentum ullamcorper. Nam imperdiet congue massa, ut tristique velit ultrices a. Vestibulum vel tincidunt neque. Nam dolor diam, aliquet id imperdiet ac, vestibulum sit amet tellus. Etiam id mi dapibus, molestie mi nec, mollis ante. Fusce scelerisque vehicula diam vel ultrices. Cras id sapien non purus malesuada volutpat eu quis felis. Nam convallis vulputate urna, dictum iaculis ex tincidunt vitae. Curabitur egestas mollis commodo. Aliquam placerat mattis suscipit.

Sed tincidunt egestas nulla, id dignissim tellus pellentesque eget. Aliquam aliquet posuere congue. Pellentesque quis aliquam metus, at tristique diam. Nam ante nulla, aliquam at magna in, ultrices suscipit velit. Nam ut metus ac ipsum varius mollis. Morbi eros lacus, aliquam quis mi at, pellentesque lacinia sem. Nulla dui urna, laoreet in ligula a, malesuada ullamcorper ante. Vivamus ultrices lobortis sem eu hendrerit. Mauris malesuada nec quam sed convallis. Integer id vehicula urna.

Curabitur finibus, magna quis tristique gravida, elit enim aliquam ante, ut ornare lorem leo ut purus. Vivamus eu hendrerit diam, sed auctor sem. Vivamus sed diam et erat consectetur tristique efficitur ut massa. Cras at aliquet massa, eget viverra ligula. Aenean posuere in lectus laoreet faucibus. Aliquam risus neque, viverra quis iaculis rutrum, suscipit id nibh. Fusce ornare venenatis dui, imperdiet mollis lacus pharetra pulvinar. Vestibulum placerat purus eu elit luctus mollis. Integer quis ligula id dui euismod auctor a ac eros. Donec fringilla lorem ac metus scelerisque ultricies. Sed turpis velit, faucibus dignissim egestas eget, commodo nec elit. Vivamus diam lectus, hendrerit vitae malesuada at, pellentesque sed tellus. Etiam ullamcorper mi ac ornare aliquet. Aenean ultricies iaculis molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pellentesque vulputate justo maximus vulputate.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam aliquam, purus a viverra venenatis, urna augue sagittis eros, eu pulvinar risus arcu et dui. Sed et velit non orci rutrum pellentesque eu et sapien. Fusce tellus diam, varius at nisl a, ornare eleifend lectus. Donec eget lobortis magna. Donec scelerisque facilisis sapien sit amet maximus. Proin pretium cursus scelerisque. Cras ut leo sapien. Ut faucibus viverra tortor. In quis est interdum, malesuada urna quis, tempus sapien. In quam quam, mollis tincidunt turpis a, dictum efficitur ipsum. Phasellus sit amet justo hendrerit, condimentum erat eget, pharetra arcu. Integer dictum non augue eu posuere. Fusce vitae bibendum purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Nam faucibus lorem vitae arcu auctor cursus. Donec et ligula lorem. Suspendisse vitae commodo erat, eu convallis magna. Nulla elit metus, malesuada et fermentum vel, feugiat facilisis velit. Nullam ac pretium tortor, et lacinia justo. Cras dictum ultricies nulla vitae lobortis. Nunc ultrices vel dolor a blandit. Duis pharetra auctor mauris, quis imperdiet leo efficitur in. Curabitur in elit sit amet dolor bibendum maximus. Morbi auctor est eget sem sagittis dignissim. In faucibus tempor justo quis vehicula. Nunc nec turpis non eros placerat tempor quis in sapien. Duis nec nisl pulvinar leo fringilla ornare. Sed elementum libero blandit ex dictum, in volutpat purus bibendum. Donec congue, quam ac pharetra tincidunt, elit urna tempor orci, sit amet dictum est augue sit amet lorem. Nunc suscipit finibus lectus, nec iaculis tellus tincidunt non.

Phasellus id risus quis est elementum suscipit. Aenean ac dapibus massa, aliquam lacinia augue. Praesent imperdiet a arcu vitae sagittis. Duis feugiat mi lacus, sed maximus metus dictum a. Nam diam odio, cursus vitae eros et, congue vehicula metus. Vivamus nec lorem blandit, viverra risus quis, faucibus elit. Integer id eros et libero aliquet egestas sed mattis sapien. Quisque eget tortor venenatis, pharetra dolor vel, pellentesque nibh. Aenean diam nulla, rhoncus quis orci vel, fringilla laoreet nunc.

Maecenas accumsan dolor ut leo tristique, et imperdiet justo commodo. Quisque dapibus, purus pellentesque aliquet accumsan, ante augue auctor nisl, et tincidunt lacus mi sit amet arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin convallis, lectus ut fringilla fringilla, ex dui blandit nisi, eu convallis ex augue vitae leo. Integer vel nibh dictum eros sodales laoreet. Proin quis velit sed nulla tempor lobortis non ut orci. Suspendisse malesuada mollis risus at sodales.

Nam quis rutrum purus. Nam lacinia nibh at nisi euismod pellentesque. In urna nulla, consequat vel gravida eget, hendrerit nec lacus. Phasellus cursus ex non finibus ornare. Curabitur blandit erat sed nulla aliquet, id tempor quam commodo. Proin quis pulvinar libero. Quisque iaculis euismod vehicula. Vestibulum lacinia iaculis leo, aliquet tristique tellus dapibus non. Vestibulum non facilisis sem, nec blandit ligula. Mauris in euismod risus. Suspendisse non felis sollicitudin, gravida purus nec, dapibus dui. Duis in arcu libero. Quisque congue consequat sem, et tempor justo mattis in. Duis venenatis ligula nec diam fermentum, vitae ornare massa posuere. Donec nec orci congue, varius ipsum nec, euismod odio. Integer sed consectetur mi.

Vestibulum venenatis consequat rutrum. Vivamus eget diam sit amet neque placerat finibus. Proin auctor, risus vel varius convallis, tortor neque semper tortor, quis vestibulum diam lorem nec urna. Vivamus suscipit mauris orci, dictum imperdiet diam tempus a. Donec nec metus at quam tincidunt placerat nec id nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras imperdiet accumsan libero vitae bibendum. In tortor enim, euismod a pretium eget, pellentesque a mi.

Nunc sagittis metus blandit elit semper maximus. Mauris eu enim non velit rutrum elementum et a erat. Praesent nec condimentum mi, at congue turpis. Fusce suscipit, ligula quis commodo euismod, augue quam fermentum purus, dapibus lacinia ligula felis eu sem. Sed pulvinar scelerisque tellus non semper. Praesent arcu tortor, egestas mattis tempus a, ullamcorper non mi. Curabitur sagittis libero eu dolor bibendum volutpat. Curabitur convallis placerat pretium. Cras nec convallis mi. Vestibulum id feugiat leo.

Nam vel orci sodales, aliquam velit sit amet, hendrerit erat. Nullam tristique tincidunt dui et semper. Nulla lobortis bibendum ipsum, at placerat neque sodales sed. Donec ullamcorper augue nibh, in euismod lorem hendrerit quis. Quisque eget erat sed justo euismod venenatis. Sed at nisl ex. Quisque et nisl rutrum, hendrerit felis sit amet, volutpat turpis. Fusce mollis vehicula leo sit amet elementum. Maecenas rutrum suscipit sollicitudin. Nullam porta libero mi, non ultrices velit sagittis ut. Vivamus nibh odio, ornare vitae arcu non, convallis scelerisque ipsum. Phasellus aliquam massa ac dolor fringilla dapibus. In ante quam, hendrerit eu mollis eget, laoreet ut urna.

Phasellus rutrum at massa ut tincidunt. Cras dapibus tincidunt lorem, sit amet finibus est suscipit et. Praesent blandit lorem eget ligula venenatis, sit amet imperdiet massa commodo. Vivamus iaculis commodo quam id tincidunt. Cras eu porttitor leo, nec volutpat augue. Vivamus ligula orci, tincidunt ac suscipit eu, sollicitudin at turpis. Morbi suscipit urna vitae gravida ullamcorper. Nam interdum tempus magna non bibendum. Donec elementum metus vel dui euismod, a porttitor ligula sodales. Etiam tempor, sapien at tincidunt mattis, mauris est semper tortor, eget elementum lectus erat ut enim. Aliquam accumsan urna id nibh luctus auctor.

Praesent est tellus, vestibulum quis tristique ut, consequat in nisl. Sed luctus, nibh id efficitur consectetur, mauris massa suscipit justo, eget accumsan tortor ante in dolor. Duis imperdiet euismod urna, eget cursus nisi tristique vitae. Vestibulum eleifend nunc in purus finibus faucibus. Praesent finibus sodales malesuada. Integer mollis risus non risus condimentum, id malesuada neque accumsan. Mauris commodo aliquam gravida. Morbi aliquam suscipit odio ac condimentum. Nunc ornare lorem metus, bibendum fermentum ex iaculis ornare. Cras tempus est metus, eu euismod dolor gravida semper. Aenean nec nibh venenatis, luctus eros id, blandit justo. Ut vitae auctor eros. Etiam sit amet neque nunc. Sed at dui a dolor egestas aliquet. Nulla cursus viverra nulla, eu sollicitudin leo pulvinar venenatis.

Aliquam faucibus euismod ex, in commodo nunc blandit eget. Phasellus ut accumsan sem. Mauris vitae mauris venenatis, dictum orci in, lobortis metus. Sed suscipit mi felis, a rutrum ante placerat et. Maecenas enim tellus, accumsan sit amet ligula ac, vestibulum maximus tortor. Donec id suscipit mauris. Integer et lectus euismod, eleifend massa et, ullamcorper justo. Donec venenatis commodo justo, nec efficitur massa eleifend a. Suspendisse sagittis metus id auctor semper. Curabitur tempus quam augue, ac sodales mauris efficitur eu. Sed aliquam justo tellus, nec lacinia lorem euismod nec.

Etiam ac tortor ornare, fringilla mauris eget, vestibulum mauris. Duis ligula neque, tincidunt eget mollis et, tempus a erat. Aliquam sit amet vestibulum dui. Sed faucibus mauris elit, ut pellentesque mi lobortis eu. Sed viverra diam sed egestas hendrerit. Nulla facilisi. Nam et turpis purus. Morbi iaculis turpis id varius gravida.

Nulla ut erat nec lorem imperdiet imperdiet. Aliquam et diam non purus bibendum laoreet. Quisque dapibus purus eget gravida ultricies. Morbi fermentum turpis ut vulputate blandit. Duis consequat porttitor neque in egestas. Vestibulum interdum urna tempor libero pretium malesuada. Fusce in elementum leo. Nulla luctus nisl diam, eget interdum orci rhoncus et. Duis dapibus augue quis feugiat feugiat. Fusce tempus eu mauris nec vehicula. Vivamus luctus quis magna in porttitor. Phasellus viverra mollis turpis. Quisque in metus leo.

Nulla luctus pharetra libero. Sed ut dictum justo. Aliquam in convallis massa, sit amet pulvinar magna. Integer euismod lacus a quam congue, eget porttitor nunc dignissim. Integer aliquet pharetra tellus id fringilla. Nam sapien enim, consequat vitae arcu sit amet, varius efficitur ante. Vestibulum vitae nulla imperdiet, facilisis lorem volutpat, volutpat sem. Vestibulum risus diam, imperdiet a efficitur et, tempor vel tellus. Morbi metus neque, tempus id diam eu, tempor porttitor nibh. Curabitur ut felis lobortis, imperdiet est in, molestie lorem. Nunc congue libero elit. Proin eu tellus in leo pellentesque tempus. Vestibulum a est et neque molestie faucibus vel sed enim. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Proin sodales tortor vel nibh suscipit, quis scelerisque mi posuere. Aenean fermentum, metus sit amet aliquet tincidunt, felis nunc varius ipsum, vel posuere velit nisl nec orci. Curabitur vitae volutpat quam, vel bibendum dolor. In ac erat purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum at mauris est. Integer pulvinar nibh justo, ac lobortis eros laoreet ut. Pellentesque pulvinar sapien id ipsum porta elementum vel sit amet purus. Vestibulum vulputate feugiat ultrices.

Nullam lorem magna, commodo vitae tempor quis, vulputate non leo. Vestibulum ac nunc luctus, vehicula nisi maximus, efficitur ligula. Curabitur aliquet tincidunt varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non lectus at odio gravida interdum at non risus. Duis aliquam auctor risus, sed facilisis ligula tempus vel. Etiam quam lorem, molestie tristique ante sit amet, tempus suscipit dui. Pellentesque iaculis metus sed lorem dignissim posuere. Integer accumsan odio lectus, a dapibus arcu mollis vel. Mauris orci massa, auctor quis pharetra id, dictum id nisl. Etiam ultrices, dolor laoreet scelerisque imperdiet, massa velit pharetra ante, laoreet tempor tortor mauris id dolor. Morbi facilisis quam nibh, non tincidunt ante imperdiet quis. Praesent venenatis, nulla at bibendum tempus, augue metus rutrum nunc, quis imperdiet quam lectus non mauris.

Aliquam cursus nisi eu dui condimentum facilisis. Maecenas nec nulla hendrerit, viverra mauris volutpat, tincidunt justo. Morbi eu diam imperdiet, posuere leo ac, viverra est. In pulvinar orci ut mollis bibendum. Morbi libero diam, fermentum at dapibus vitae, euismod eu quam. Donec at diam ut arcu posuere faucibus. Nam fringilla in lorem non tincidunt. Duis ac elit enim. Nullam ullamcorper, ipsum id suscipit malesuada, quam nibh tempus tortor, ut convallis ante massa ut felis. Praesent elementum semper purus eu placerat. Vivamus in commodo sem. Fusce in convallis sapien. Mauris ultrices dictum eros a laoreet. Phasellus molestie augue eu tincidunt ultricies. Phasellus vel dui posuere, egestas ligula nec, efficitur nibh.

Ut nibh lectus, rhoncus ac dolor nec, euismod interdum felis. Sed quis suscipit nisl. Donec nisl lorem, cursus a dui a, vehicula elementum quam. Aliquam ultrices facilisis aliquet. Integer arcu augue, tincidunt malesuada sollicitudin non, pretium ac sem. Donec pharetra diam felis, vel commodo nulla lobortis eget. Curabitur ipsum lorem, eleifend non massa in, porta ornare lectus. Nullam fermentum orci arcu, eu pretium libero laoreet non. Sed faucibus justo in enim cursus, sed vulputate nisi venenatis.

Donec vehicula lorem ullamcorper risus auctor, a elementum purus vulputate. Fusce tincidunt cursus sollicitudin. Etiam arcu mi, commodo eu orci vitae, sodales commodo neque. Curabitur pretium ex et arcu consectetur, quis auctor ante facilisis. Phasellus rutrum pharetra mauris non blandit. Sed maximus pretium orci, ut consequat libero eleifend in. Etiam sit amet purus ut urna eleifend ullamcorper vitae eget quam.

Mauris quis tincidunt ante. Nullam nec elit auctor, euismod tellus ac, ullamcorper purus. Quisque mi augue, pulvinar sed efficitur iaculis, sagittis at velit. Quisque convallis mauris tristique, volutpat nibh eget, lobortis lorem. Curabitur eu maximus risus, non tincidunt nulla. Ut ac condimentum turpis, quis tristique risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus sed pulvinar metus, vel elementum nibh. Pellentesque vestibulum nunc justo, eu tincidunt ipsum auctor ac. Phasellus at semper est. Phasellus augue nisi, dictum vitae tincidunt vestibulum, ullamcorper a eros. Maecenas felis nunc, interdum vel velit id, pellentesque lacinia orci. Nunc sit amet cursus nunc. Vestibulum rhoncus scelerisque est vitae sagittis. Aenean in feugiat orci.

Morbi non elementum arcu. Etiam blandit ac libero vitae congue. Integer odio ex, vulputate eget neque in, scelerisque vestibulum dolor. Mauris sollicitudin imperdiet urna, sed scelerisque risus porttitor eget. Sed aliquet semper vestibulum. Donec nec ex a lorem cursus interdum. Duis lorem ex, maximus id facilisis eget, luctus et ligula. Donec turpis dui, sagittis a tincidunt eget, feugiat id lacus. Ut efficitur sem lacus, sed mollis ex malesuada id. Phasellus mollis mollis diam a consectetur. Morbi odio nulla, efficitur vel viverra nec, faucibus eget metus. Duis aliquet ligula dolor, sit amet gravida tellus ullamcorper non. Etiam sagittis odio id ante posuere imperdiet. Suspendisse vehicula hendrerit varius. Donec neque ipsum, scelerisque at fringilla vitae, fringilla sed augue. Nam quis dolor nisl.

Curabitur eget tellus sed leo tempor congue. Praesent at quam ac lorem placerat mattis sit amet vitae massa. Phasellus suscipit condimentum ante, ut rutrum ipsum. Curabitur sapien ex, placerat et felis non, sodales accumsan velit. Sed eu feugiat sem, congue mollis quam. Phasellus malesuada aliquet arcu vel accumsan. Ut commodo tincidunt urna in faucibus. Aliquam enim tortor, dictum eget vestibulum maximus, fermentum vitae metus. Curabitur rutrum diam a venenatis mattis.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis imperdiet auctor augue, eu dignissim est varius eu. Aenean lacinia dui mauris, vitae accumsan enim sagittis vel. Vestibulum elementum justo vel eros sodales accumsan. Proin vitae est nec justo auctor consectetur eget id massa. Mauris aliquet enim lorem, ac bibendum augue aliquet vel. Nam molestie scelerisque sem id vehicula. Quisque et risus hendrerit, iaculis odio ac, ultricies diam. Vestibulum velit nibh, aliquam sed quam id, imperdiet fringilla metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent tristique, ligula in commodo consequat, odio nisl eleifend augue, id gravida erat est vitae orci. Curabitur sed justo elit.

Sed ornare sollicitudin nunc, vel tempor nulla consectetur eu. Nam sit amet aliquet lorem. Integer sed ligula justo. Duis accumsan lectus ac scelerisque vehicula. Nunc vel est ultricies, euismod metus ac, dapibus justo. Etiam eget faucibus ligula. Donec ut lorem elementum, congue ante nec, dignissim lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut elit et metus lacinia ullamcorper sed gravida velit. Curabitur ac justo sed dolor scelerisque ullamcorper. Maecenas egestas suscipit arcu sit amet scelerisque. Sed justo enim, pulvinar id est eu, convallis feugiat orci. Pellentesque lacinia eleifend pellentesque.

Aenean mollis posuere nisl sed pretium. Duis massa lacus, varius vitae condimentum in, condimentum vitae orci. Sed consequat leo quis nunc dictum hendrerit. Nullam venenatis eget felis sed semper. Integer gravida mollis sapien, ac sodales elit. Donec non diam sollicitudin, bibendum erat vel, aliquet est. Aenean vulputate urna eros. Cras consequat maximus risus quis imperdiet. Vestibulum cursus mattis neque at tempus. Vivamus elit nisi, ultricies id facilisis a, vulputate non augue. Curabitur sollicitudin nisi quis felis sollicitudin imperdiet. Integer non ligula pretium, imperdiet urna tincidunt, gravida augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent efficitur tortor vitae nunc sodales, eget rhoncus lorem euismod. Mauris vestibulum ornare gravida.

Suspendisse in felis quis quam scelerisque ullamcorper id id odio. Nulla aliquam tincidunt turpis, ut sollicitudin lorem viverra a. Phasellus quis ante vel turpis sollicitudin vulputate vel id eros. Morbi ut ex nulla. Cras id arcu a nisi dapibus blandit. Nam gravida odio ut massa interdum auctor. Maecenas ultricies leo porttitor massa pretium tincidunt. Phasellus faucibus eget augue ac molestie. Nam vel dignissim massa. Nunc id ultrices libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus faucibus elit id feugiat hendrerit.

Fusce eu pellentesque arcu, vel placerat erat. Vestibulum quis dictum tellus. Sed a odio diam. Sed commodo diam ut ex rhoncus viverra. Proin et dui facilisis, facilisis turpis sed, iaculis odio. Mauris nec metus tempus, rhoncus dui et, mattis lorem. Aliquam id laoreet est, eu consequat tellus. Mauris auctor risus in diam pellentesque, in dictum mi scelerisque. Nullam nec magna euismod, congue magna sed, rhoncus quam. Maecenas risus risus, blandit ac arcu a, interdum accumsan eros. Nam non leo aliquam, fringilla odio sit amet, vulputate ex. Praesent feugiat ipsum magna, non volutpat libero aliquet id. Sed turpis felis, venenatis et ante vitae, dictum convallis leo. Nulla id imperdiet purus, vel hendrerit diam. Nullam viverra ante ut eleifend blandit.

Vestibulum id rutrum erat. Ut non lobortis ipsum. Proin ultricies lobortis neque eget vestibulum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate eros eu risus maximus, eu sagittis mauris laoreet. Cras lobortis eros quam, in faucibus lacus malesuada et. Etiam purus arcu, aliquet et vehicula in, scelerisque et turpis. Aliquam erat volutpat. Nunc volutpat diam ac sem sodales mattis. Donec sed tortor condimentum, semper ante ac, blandit erat. Aenean viverra turpis mauris. Sed vitae congue lectus, id commodo enim. Sed in venenatis nulla. Cras vulputate tortor et neque auctor, vel dictum arcu semper.

Mauris mi orci, luctus vel lobortis in, ullamcorper sit amet justo. Donec porttitor, dolor nec vestibulum congue, odio risus scelerisque lorem, quis euismod nisl nibh vitae felis. Suspendisse velit tortor, consequat nec nisl sit amet, vulputate elementum nisi. Vestibulum at felis arcu. Nullam molestie finibus venenatis. Quisque at nibh ipsum. Integer et ultricies lorem. Pellentesque eget lacus vel odio ullamcorper mattis. Vestibulum ullamcorper placerat sollicitudin. Donec quis mauris sem. Curabitur bibendum libero nec nunc commodo condimentum. Morbi rutrum tortor libero, vitae convallis nisi porttitor ut. Morbi sem ipsum, suscipit quis accumsan vitae, pretium vel quam. Proin a felis tincidunt, tristique sem a, pharetra urna. Sed condimentum felis sit amet porttitor pharetra. Nam maximus tortor ut imperdiet viverra.

Morbi ullamcorper nulla arcu, vitae sagittis ipsum eleifend vel. Nullam congue tempus libero quis hendrerit. Vestibulum a velit vel lorem dapibus blandit id sit amet purus. Donec eu convallis eros, vitae tincidunt leo. Quisque lobortis imperdiet est, at molestie dui pulvinar non. Pellentesque bibendum ex quis ultricies rutrum. Etiam ipsum erat, sollicitudin pretium felis a, sagittis feugiat sapien. Aliquam vulputate massa eu mi pulvinar, sit amet auctor felis gravida. Praesent tincidunt ligula elit, eu imperdiet ex vulputate eget. Ut aliquet risus iaculis metus viverra, quis posuere lorem imperdiet. Proin vestibulum lacus velit, vitae ornare sapien lacinia quis.

Praesent dictum venenatis dolor ornare congue. Sed accumsan eget risus eget laoreet. Vestibulum interdum nunc ante, nec ornare erat vehicula nec. Ut efficitur dui ex, sit amet blandit ante aliquet ut. Maecenas nisl tortor, ultricies at imperdiet ut, condimentum ac neque. Morbi auctor vitae est sit amet dictum. Sed in hendrerit nulla, eget facilisis diam. Pellentesque scelerisque orci lorem, sit amet tincidunt dolor dictum consequat. Maecenas id imperdiet turpis, at lacinia elit. Cras porta egestas arcu, at porttitor metus volutpat facilisis. Pellentesque in tristique felis. Nam lobortis lorem pretium metus rutrum rutrum. Curabitur eu augue leo. Aliquam cursus efficitur tortor sit amet pretium. Aenean massa sapien, rhoncus nec facilisis nec, rutrum at enim. In suscipit feugiat odio, sit amet scelerisque mi pellentesque eget.

Nam convallis pharetra neque, et dignissim urna cursus nec. Vestibulum placerat lacus nec tellus sollicitudin pretium. Proin semper eget ex at tincidunt. Duis lobortis tempor sodales. Nam cursus lacinia ante, nec fringilla lacus ullamcorper id. In hendrerit odio a libero sollicitudin, sed vehicula massa auctor. Nunc vehicula interdum turpis sit amet ultrices. Duis ullamcorper, libero vitae rutrum rutrum, metus tortor varius arcu, ac ullamcorper felis quam sed nunc. In risus purus, faucibus in tempor et, porttitor quis velit.

Sed id feugiat velit. Ut semper rutrum metus, in malesuada sapien rhoncus a. Phasellus rhoncus efficitur eros vitae placerat. Vivamus faucibus neque et turpis feugiat, eu faucibus sem lobortis. Praesent faucibus, erat non maximus scelerisque, urna enim commodo lacus, nec aliquam leo lectus sit amet purus. Nulla facilisi. Vivamus at ex eu sem pellentesque commodo. Sed luctus orci sit amet dolor condimentum, at efficitur nisi vestibulum. Suspendisse turpis nunc, congue a vehicula vel, pellentesque quis ante. In imperdiet fringilla sapien, at sodales enim auctor eget. Donec nibh ex, venenatis non pulvinar id, ullamcorper id tellus. Sed venenatis gravida lacus, eget pretium ex viverra quis. Curabitur quis erat in orci molestie accumsan vitae egestas enim. Quisque quis posuere massa.

Aenean eget elit ut dui vestibulum aliquam a ut turpis. Praesent ac ante placerat, tincidunt est ut, tristique neque. Nulla a finibus mauris, pretium ornare massa. Quisque sit amet velit in felis convallis elementum id id nisi. Aliquam auctor viverra iaculis. Ut varius enim justo, vitae efficitur ex dignissim at. Proin at ipsum ultricies metus porta tincidunt. Praesent laoreet libero arcu, vitae dictum neque egestas eget. Nullam eleifend egestas mauris, at vehicula sapien fringilla ut. In porta magna ac libero vestibulum imperdiet.

Nam porta lacinia tortor, eu egestas arcu imperdiet sit amet. Pellentesque a pellentesque nisl. Nulla ut finibus purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed bibendum dolor eu lacus imperdiet venenatis. Nunc quis lectus vehicula, faucibus diam eu, luctus dolor. Aliquam et luctus tellus. Donec sed pretium est, vitae maximus magna. Aliquam interdum orci ligula, a sagittis risus imperdiet non.

Pellentesque et fringilla ante, a consectetur lacus. Sed ultricies feugiat ex at facilisis. Vestibulum accumsan enim eget nisi porta, at gravida lacus consequat. Morbi semper sem purus, quis hendrerit sem fringilla eu. Proin vitae vestibulum tellus. Cras lectus velit, pulvinar vitae venenatis vestibulum, tempus eu odio. Maecenas auctor pulvinar ex, ut malesuada sapien volutpat in. Vivamus blandit lectus vitae ultricies efficitur. Pellentesque rutrum risus eros, sit amet mollis mi dictum a. Praesent vel iaculis ligula.

Donec vel arcu consequat ligula laoreet ultricies non sodales sapien. Morbi laoreet consequat elit vitae eleifend. Etiam tellus libero, egestas non erat in, convallis fermentum justo. Praesent vitae arcu quis diam hendrerit consequat. Curabitur ullamcorper, nisl id imperdiet volutpat, dui leo placerat purus, ut gravida tortor mauris sed augue. Ut quis auctor diam, at efficitur metus. Nullam in nisl nunc. Nam faucibus, urna in euismod cursus, nulla ligula lobortis elit, quis cursus nunc elit quis ligula. Pellentesque vestibulum velit est, non porta lectus eleifend ac. Sed suscipit ultrices enim vel gravida. Proin rhoncus nisl et erat eleifend auctor. Integer sed mattis tellus. Mauris bibendum ante non hendrerit sodales. In luctus congue massa, ac ultricies nibh iaculis eget.

Vivamus vitae mi purus. Proin at lobortis arcu, in fermentum ligula. Phasellus bibendum tortor at mattis volutpat. Proin at enim bibendum, maximus augue quis, luctus arcu. Morbi lobortis tortor orci, sed hendrerit augue tempor ac. Nullam at viverra leo, id vulputate quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sit amet ex id facilisis. Vivamus efficitur gravida nibh eu tempor. Curabitur facilisis ex a tellus auctor, et ultrices urna eleifend. Aenean vulputate, tellus ut pretium efficitur, lorem sapien blandit neque, a pretium sapien mauris vel purus. Duis purus felis, tincidunt ac porta a, posuere quis dui. Vivamus in luctus dui, a ornare ligula. Sed ac sollicitudin libero.

Maecenas ac dui a tellus lobortis varius. Mauris sodales dictum sem, vitae fermentum lectus. Donec at neque et massa commodo semper. Sed egestas aliquet quam, non rutrum dui. Nulla in est ut orci finibus faucibus. Integer vitae tortor nec diam mollis viverra. Maecenas vel massa finibus ligula cursus faucibus. Aliquam pellentesque augue id elementum malesuada. In id posuere libero, quis luctus dui. Donec vitae neque id ipsum faucibus maximus id pharetra justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum vitae volutpat magna. Mauris eget tincidunt nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse potenti.

Curabitur libero diam, lobortis id ipsum quis, bibendum malesuada sapien. Vivamus porta posuere pretium. Mauris rhoncus tellus nec dui feugiat, a dignissim mauris porta. Curabitur lacinia metus elit, pharetra gravida ligula vehicula et. Duis in auctor tellus, faucibus porta ipsum. Morbi non mauris congue, tempor massa eget, tincidunt ante. Mauris eget vestibulum velit, id feugiat turpis. Phasellus iaculis pretium mauris non accumsan. Nullam bibendum sollicitudin augue eget viverra. Vestibulum lobortis eros ac nulla ullamcorper pulvinar. Suspendisse non volutpat metus. Ut porta turpis quis sodales vehicula. Donec mollis neque lorem, in rhoncus lacus tincidunt sit amet. Donec tempor mattis quam vitae placerat.

Mauris sagittis leo ut turpis ultrices vestibulum. Praesent a commodo quam. Aliquam pulvinar nulla vel vestibulum vulputate. Maecenas feugiat ligula eu risus pulvinar fermentum. Fusce id sem fermentum enim pharetra posuere. Mauris et dui sit amet nulla aliquet sollicitudin et eget ex. Nunc consequat augue dolor, nec consectetur odio viverra molestie. Nam tincidunt orci ac felis posuere, sit amet sodales tellus mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam convallis lectus eget ipsum bibendum vehicula. Cras dignissim ornare urna at ornare. Proin efficitur, ex condimentum sagittis aliquet, orci tellus placerat magna, a vestibulum tellus metus ut ligula. Morbi eu risus quis arcu imperdiet viverra eget et neque. Praesent sed rutrum velit. Nunc sed turpis sit amet turpis faucibus eleifend non vel lectus. Maecenas rutrum lacinia nisl, id consequat lectus pharetra vel.

Aenean eleifend efficitur molestie. Proin molestie pulvinar velit, at ultrices diam porta at. Nulla egestas enim ut massa feugiat iaculis. Sed ac nisi sagittis, faucibus mauris vitae, lobortis mauris. Fusce molestie, neque non sodales dictum, felis enim varius ligula, non efficitur tellus nisl eu leo. Morbi laoreet, dui sed mattis laoreet, tortor dui luctus sapien, eget feugiat turpis ex vel purus. Ut a nisl gravida leo bibendum volutpat at non sapien. Aliquam ornare suscipit lectus, eu maximus nunc semper quis. Nullam pulvinar laoreet velit vel tincidunt. Donec vel sem blandit, cursus lacus a, vestibulum augue. Donec scelerisque lectus risus, in mattis tellus faucibus et. Curabitur vitae volutpat sem, ut tempor urna. Suspendisse purus libero, rhoncus at dolor nec, auctor bibendum mi. In non ligula dignissim, posuere ligula id, pellentesque est. Phasellus malesuada libero lacinia, ornare sapien a, vestibulum leo. Cras sodales convallis turpis eget hendrerit.

Nullam dapibus, leo vel venenatis pulvinar, urna tellus dapibus nisi, rutrum tempor augue sem ac mauris. Vivamus sed egestas sem. Nullam dictum vel erat a imperdiet. Praesent convallis felis ac lorem sollicitudin, ac tempor dolor sagittis. Nam a nulla porta, tincidunt sem eget, viverra orci. Donec congue est sed lacus iaculis, ut blandit sapien mattis. Proin pretium ex nec odio accumsan, quis hendrerit lacus laoreet. Ut eu quam a ex mattis iaculis. Suspendisse potenti. Proin non facilisis ipsum, sit amet dictum urna. Nulla facilisi. Mauris ornare sed nulla at tincidunt. Proin varius facilisis vehicula. Etiam condimentum pulvinar risus, eu vestibulum orci. Cras neque felis, lacinia quis interdum ut, molestie consectetur ante. Vestibulum id est eget justo varius venenatis.

Pellentesque nec odio eget lectus suscipit ultricies. In sodales egestas ipsum, ut sollicitudin erat sagittis sit amet. Sed aliquet nulla sit amet libero volutpat, ac pulvinar neque aliquet. Vestibulum eget eros mauris. Nunc interdum ante a turpis vulputate, ut mollis tortor convallis. Integer ullamcorper, ipsum in rhoncus viverra, purus erat condimentum est, nec tempor nunc magna non erat. Aliquam erat volutpat. Quisque tempor placerat mollis. Aenean bibendum mauris ac libero porttitor, sit amet tincidunt eros pretium. Fusce ac blandit tellus, eget facilisis est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed ut ipsum mattis, suscipit lectus vitae, luctus tortor. Phasellus vel enim dictum eros fermentum blandit.

Duis volutpat erat id mauris aliquet, vel commodo est mattis. Pellentesque quis hendrerit eros, sed rutrum justo. Suspendisse finibus, nisl nec dictum viverra, ex tellus fringilla lorem, id dignissim odio turpis id augue. Sed auctor venenatis purus, at porta ligula dapibus maximus. Donec pretium pellentesque congue. Sed vulputate cursus rhoncus. Maecenas sed porta nisi, et aliquam nulla. Fusce ac ex sem. Morbi nec quam lectus. Duis massa turpis, lacinia nec justo auctor, blandit molestie velit. Nunc varius, sem quis malesuada aliquet, metus libero dictum mauris, a tristique libero mi finibus neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac consectetur dui.

Nunc pretium, enim eu viverra ultricies, sapien mi mollis sem, vel bibendum nisi orci vitae ligula. Donec ligula est, dignissim quis enim in, ultricies dignissim tellus. Cras pretium diam sed quam laoreet gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce vestibulum tincidunt convallis. Maecenas lacinia nulla ultrices quam aliquam, eget scelerisque orci hendrerit. In in odio a mauris ultrices placerat ut ac ligula. Donec accumsan id purus sed scelerisque. Nam ac nisi id nulla condimentum ultricies in ac enim.

Curabitur aliquet diam in urna bibendum, sed placerat quam condimentum. Fusce suscipit egestas bibendum. Nulla congue tincidunt consequat. Vivamus mollis ipsum blandit tincidunt lacinia. Cras feugiat augue eget eleifend feugiat. Cras tristique elit nec luctus convallis. Nulla metus leo, bibendum ac mattis ut, elementum in quam. Sed in ipsum egestas nibh dictum feugiat sit amet et felis. Suspendisse suscipit a magna vitae ultricies. Sed sem neque, tincidunt sit amet orci non, lacinia gravida dui. Sed sodales, nunc sit amet cursus dapibus, nunc massa imperdiet leo, vitae viverra ex leo at ligula. Suspendisse non convallis augue."""

import re

text_split = [[[ re.sub('[,.!?]','',w) for w in par.split(' ')] for sen in par.split('.')] for par in text.split('\n') if par]

print(tf.ragged.constant([[[1],[2],[3]],[[2]]]).shape)

tf_text = tf.ragged.constant(text_split)

print(tf_text.shape)

print(tf_text[::35,-1:,:3])

[[[w.lower() for w in s] for s in p] for p in text_split]

print(timeit.timeit(lambda: [[[w.lower() for w in s] for s in p] for p in text_split], number = 100))

tf.ragged.map_flat_values(tf.strings.lower, tf_text)

print(timeit.timeit(lambda: tf.ragged.map_flat_values(tf.strings.lower, tf_text), number = 100))


